#!/usr/bin/env python3
# Generate include/version_gen.h with timestamp version + build epoch.
from __future__ import annotations

import argparse
import os
from datetime import datetime, timezone

EXPIRE_DAYS = 90
CONTACT_EMAIL = "yanggan2015@foxmail.com"
RELEASES_URL = "https://github.com/yanggan2015/relay-c-releases/releases"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", default="include/version_gen.h")
    ap.add_argument("--stamp", default="", help="Override version stamp YYYYMMDD-HHMMSS")
    ap.add_argument(
        "--epoch",
        type=int,
        default=0,
        help="Override build unix epoch (UTC). 0 = use now / stamp.",
    )
    args = ap.parse_args()

    now = datetime.now(timezone.utc)
    stamp = args.stamp.strip()
    if stamp:
        try:
            now = datetime.strptime(stamp, "%Y%m%d-%H%M%S").replace(tzinfo=timezone.utc)
        except ValueError as exc:
            raise SystemExit(f"invalid stamp {stamp!r}: {exc}") from exc
    else:
        stamp = now.strftime("%Y%m%d-%H%M%S")

    epoch = int(args.epoch) if args.epoch > 0 else int(now.timestamp())
    build_iso = datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    expire_epoch = epoch + EXPIRE_DAYS * 24 * 3600
    expire_iso = datetime.fromtimestamp(expire_epoch, tz=timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )

    content = f"""/* Auto-generated by tools/gen_version.py — do not edit. */
#ifndef RELAY_VERSION_GEN_H
#define RELAY_VERSION_GEN_H

#define APP_VERSION_STRING "{stamp}"
#define APP_BUILD_TIME_UTC "{build_iso}"
#define APP_BUILD_EPOCH {epoch}LL
#define APP_EXPIRE_DAYS {EXPIRE_DAYS}
#define APP_EXPIRE_EPOCH {expire_epoch}LL
#define APP_EXPIRE_TIME_UTC "{expire_iso}"
#define APP_CONTACT_EMAIL "{CONTACT_EMAIL}"
#define APP_RELEASES_URL "{RELEASES_URL}"

#endif
"""
    out = args.output
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    os.replace(tmp, out)

    stamp_path = os.path.join(os.path.dirname(out) or ".", "..", "output", "VERSION.txt")
    stamp_path = os.path.normpath(stamp_path)
    try:
        os.makedirs(os.path.dirname(stamp_path), exist_ok=True)
        with open(stamp_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(stamp + "\n")
            f.write(f"build_utc={build_iso}\n")
            f.write(f"expire_utc={expire_iso}\n")
            f.write(f"expire_days={EXPIRE_DAYS}\n")
    except OSError:
        pass

    print(f"wrote {out}")
    print(f"version={stamp}")
    print(f"build_utc={build_iso}")
    print(f"expire_utc={expire_iso}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
