#include "http_pages.h"
#include "util.h"
#include "mongoose.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void relay_http_page_config(struct mg_connection *c, RelayHttpServer *srv) {
    char *html;
    size_t cap = 65536;
    size_t pos = 0;
    (void)srv;

    html = (char *)malloc(cap);
    if (!html) {
        mg_http_reply(c, 500, "", "oom");
        return;
    }

    pos += (size_t)snprintf(html + pos, cap - pos, "%s%s",
        relay_page_head("Relay-C Config"), relay_page_nav("config"));

    pos += (size_t)snprintf(html + pos, cap - pos,
        "<section class=\"config-layout\">"
        "<div class=\"config-cols\">"
        "<div class=\"config-col\">"
        "<article class=\"card\">"
        "<h2>Relays</h2>"
        "<p class=\"sub\">点击条目，在下方编辑；未选择时为新建。</p>"
        "<div id=\"relayList\"></div>"
        "</article>"
        "<article class=\"card\">"
        "<h2>Relay 编辑器</h2>"
        "<p id=\"relayEditorHint\" class=\"editor-hint\">模式：新建</p>"
        "<p class=\"sub\">windows_port / linux_port 自动探测本机串口。</p>"
        "<div class=\"form-grid\">"
        "<div><span class=\"label\">name / new_name</span><input id=\"relayName\"/></div>"
        "<div><span class=\"label\">enabled</span><select id=\"relayEnabled\"><option value=\"true\">true</option><option value=\"false\">false</option></select></div>"
        "<div><span class=\"label\">windows_port</span><select id=\"relayWinPort\"></select></div>"
        "<div><span class=\"label\">linux_port</span><select id=\"relayLinuxPort\"></select></div>"
        "<div><span class=\"label\">relay_channels</span><select id=\"relayChannels\"></select></div>"
        "<div><span class=\"label\">baudrate</span><select id=\"relayBaud\"></select></div>"
        "<div><span class=\"label\">io_inverted</span><select id=\"relayIoInv\"><option value=\"false\">false</option><option value=\"true\">true</option></select></div>"
        "<div><span class=\"label\">startup_init</span><select id=\"relayStartup\"><option value=\"none\">none</option><option value=\"off\">off</option><option value=\"on\">on</option></select></div>"
        "</div>"
        "<button class=\"primary\" onclick=\"createRelay()\">创建</button>"
        "<button class=\"warn\" onclick=\"updateRelay()\">更新</button>"
        "<button class=\"ghost\" onclick=\"clearRelayEditor()\">清空</button>"
        "<button class=\"ghost\" onclick=\"reloadPorts()\">刷新串口</button>"
        "<div id=\"relayStatus\" class=\"status\"></div>"
        "</article>"
        "</div>"

        "<div class=\"config-col\">"
        "<article class=\"card\">"
        "<h2>Boards</h2>"
        "<p class=\"sub\">点击条目，在下方编辑；未选择时为新建。</p>"
        "<div id=\"boardList\"></div>"
        "</article>"
        "<article class=\"card\">"
        "<h2>Board 编辑器</h2>"
        "<p id=\"boardEditorHint\" class=\"editor-hint\">模式：新建</p>"
        "<p class=\"sub\">reset / upgrade_mode 固定时序；actions 为 JSON 自定义动作。</p>"
        "<div class=\"form-grid\">"
        "<div><span class=\"label\">name / new_name</span><input id=\"boardName\"/></div>"
        "<div><span class=\"label\">enabled</span><select id=\"boardEnabled\"><option value=\"true\">true</option><option value=\"false\">false</option></select></div>"
        "<div><span class=\"label\">reset relay</span><select id=\"boardResetRelay\"></select></div>"
        "<div><span class=\"label\">reset channel</span><select id=\"boardResetCh\"></select></div>"
        "<div><span class=\"label\">reset hold_seconds</span><select id=\"boardResetHold\"></select></div>"
        "<div><span class=\"label\">reset polarity_inverted</span><select id=\"boardResetPol\"><option value=\"false\">false</option><option value=\"true\">true</option></select></div>"
        "<div><span class=\"label\">upgrade enabled</span><select id=\"boardUpgEn\"><option value=\"true\">true</option><option value=\"false\">false</option></select></div>"
        "<div><span class=\"label\">upgrade relay</span><select id=\"boardUpgRelay\"></select></div>"
        "<div><span class=\"label\">upgrade channel</span><select id=\"boardUpgCh\"></select></div>"
        "<div><span class=\"label\">upgrade polarity_inverted</span><select id=\"boardUpgPol\"><option value=\"false\">false</option><option value=\"true\">true</option></select></div>"
        "</div>"
        "<div style=\"margin-top:10px\"><span class=\"label\">actions (JSON)</span>"
        "<textarea id=\"boardActions\" placeholder=\"{&quot;fan_on&quot;:{&quot;enabled&quot;:true,&quot;label&quot;:&quot;风扇&quot;,&quot;relay&quot;:&quot;com18&quot;,&quot;channel&quot;:2,&quot;mode&quot;:&quot;hold_on&quot;}}\"></textarea></div>"
        "<button class=\"primary\" onclick=\"createBoard()\">创建</button>"
        "<button class=\"warn\" onclick=\"updateBoard()\">更新</button>"
        "<button class=\"ghost\" onclick=\"clearBoardEditor()\">清空</button>"
        "<div id=\"boardStatus\" class=\"status\"></div>"
        "</article>"
        "</div>"
        "</div>"

        "<article class=\"card\">"
        "<h2>Server</h2>"
        "<div class=\"form-grid\">"
        "<div><span class=\"label\">http port（保存后需重启生效）</span><input id=\"serverPort\" type=\"number\" min=\"1\" max=\"65535\"/></div>"
        "<div><span class=\"label\">config path</span><input id=\"configPath\" readonly/></div>"
        "</div>"
        "<button class=\"warn\" onclick=\"saveServerPort()\">保存端口</button>"
        "<button class=\"ghost\" onclick=\"reloadConfig()\">热重载 boards.json</button>"
        "<div id=\"serverStatus\" class=\"status\"></div>"
        "</article>"
        "</section>"

        "<script>"
        "let editingRelay='', editingBoard='', latestRelays={}, latestBoards={};"
        "let detectedPorts={windows_ports:[],linux_ports:[],platform:''};"
        "function st(id,ok,t){const e=document.getElementById(id);e.className=ok?'status ok':'status err';e.textContent=t;}"
        "function qs(p){return new URLSearchParams(p).toString();}"
        "function sortComPorts(arr){"
        "  return arr.slice().sort((a,b)=>{"
        "    const na=parseInt(String(a).replace(/^COM/i,''),10)||99999;"
        "    const nb=parseInt(String(b).replace(/^COM/i,''),10)||99999;"
        "    return na-nb||String(a).localeCompare(String(b));"
        "  });"
        "}"
        "function fillSelect(id,values,emptyLabel){"
        "  const el=document.getElementById(id); if(!el)return;"
        "  el.innerHTML='';"
        "  if(emptyLabel!==null&&emptyLabel!==undefined){"
        "    const o=document.createElement('option'); o.value=''; o.textContent=emptyLabel; el.appendChild(o);"
        "  }"
        "  values.forEach(v=>{const o=document.createElement('option'); o.value=String(v); o.textContent=String(v); el.appendChild(o);});"
        "}"
        "function setSelect(id,val){"
        "  const el=document.getElementById(id); if(!el)return;"
        "  const s=(val===null||val===undefined)?'':String(val);"
        "  if(s&&!Array.from(el.options).some(o=>o.value===s)){"
        "    const o=document.createElement('option'); o.value=s; o.textContent=s+' (当前)'; el.appendChild(o);"
        "  }"
        "  el.value=s;"
        "}"
        "function initStaticSelects(){"
        "  fillSelect('relayChannels',Array.from({length:16},(_,i)=>i+1),null);"
        "  fillSelect('relayBaud',[2400,4800,9600,19200,38400,57600,115200,230400,460800,921600],null);"
        "  setSelect('relayChannels','1'); setSelect('relayBaud','9600');"
        "  fillSelect('boardResetHold',['0.5','1','2','3','5','10','15','30'],null);"
        "  setSelect('boardResetHold','5');"
        "  document.getElementById('boardResetRelay').onchange=refreshBoardChannelSelects;"
        "  document.getElementById('boardUpgRelay').onchange=refreshBoardChannelSelects;"
        "}"
        "function refreshPortSelects(){"
        "  const win=new Set(detectedPorts.windows_ports||[]);"
        "  const lin=new Set(detectedPorts.linux_ports||[]);"
        "  Object.values(latestRelays).forEach(cfg=>{"
        "    if(cfg.windows_port)win.add(cfg.windows_port);"
        "    if(cfg.linux_port)lin.add(cfg.linux_port);"
        "  });"
        "  const curWin=document.getElementById('relayWinPort').value;"
        "  const curLinux=document.getElementById('relayLinuxPort').value;"
        "  fillSelect('relayWinPort',sortComPorts([...win]),'(未设置)');"
        "  fillSelect('relayLinuxPort',[...lin].sort(),'(未设置)');"
        "  if(curWin)setSelect('relayWinPort',curWin);"
        "  if(curLinux)setSelect('relayLinuxPort',curLinux);"
        "}"
        "async function loadPortSelects(){"
        "  try{"
        "    const r=await fetch('/api/serial/ports');"
        "    detectedPorts=await r.json();"
        "  }catch(e){detectedPorts={windows_ports:[],linux_ports:[],platform:''};}"
        "  refreshPortSelects();"
        "}"
        "async function reloadPorts(){"
        "  await loadPortSelects();"
        "  const n=(detectedPorts.windows_ports||[]).length+(detectedPorts.linux_ports||[]).length;"
        "  st('relayStatus',true,'串口列表已刷新，探测到 '+n+' 个');"
        "}"
        "function refreshBoardRelaySelects(){"
        "  const names=Object.keys(latestRelays);"
        "  ['boardResetRelay','boardUpgRelay'].forEach(id=>{"
        "    const el=document.getElementById(id); if(!el)return;"
        "    const cur=el.value;"
        "    el.innerHTML='<option value=\"\">(选择 relay)</option>';"
        "    names.forEach(n=>{const o=document.createElement('option'); o.value=n; o.textContent=n; el.appendChild(o);});"
        "    if(cur)setSelect(id,cur);"
        "  });"
        "  refreshBoardChannelSelects();"
        "}"
        "function refreshBoardChannelSelects(){"
        "  [['boardResetCh','boardResetRelay'],['boardUpgCh','boardUpgRelay']].forEach(([chId,relayId])=>{"
        "    const el=document.getElementById(chId); if(!el)return;"
        "    const cur=el.value||'1';"
        "    const relayName=document.getElementById(relayId).value;"
        "    const cfg=latestRelays[relayName];"
        "    const maxCh=(cfg&&cfg.relay_channels)?cfg.relay_channels:16;"
        "    el.innerHTML='';"
        "    for(let i=1;i<=maxCh;i++){const o=document.createElement('option'); o.value=String(i); o.textContent=String(i); el.appendChild(o);}"
        "    setSelect(chId,cur);"
        "  });"
        "}"
        "function updateEditorHints(){"
        "  document.getElementById('relayEditorHint').textContent=editingRelay?'模式：编辑 · '+editingRelay:'模式：新建';"
        "  document.getElementById('boardEditorHint').textContent=editingBoard?'模式：编辑 · '+editingBoard:'模式：新建';"
        "}"
        "function updateListSelection(){"
        "  document.querySelectorAll('#relayList .chip').forEach(el=>el.classList.toggle('active',el.dataset.name===editingRelay));"
        "  document.querySelectorAll('#boardList .chip').forEach(el=>el.classList.toggle('active',el.dataset.name===editingBoard));"
        "}"
        "async function loadMeta(){"
        "  const h=await fetch('/api/health');const d=await h.json();"
        "  document.getElementById('configPath').value=d.config_path||'';"
        "  document.getElementById('serverPort').value=d.http_port||'';"
        "}"
        "async function loadLists(){"
        "  const [rr,bb]=await Promise.all([fetch('/api/config/relays'),fetch('/api/boards')]);"
        "  const rd=await rr.json(), bd=await bb.json();"
        "  latestRelays=rd.relays||{}; latestBoards=bd.boards||{};"
        "  const rl=document.getElementById('relayList'); rl.innerHTML='';"
        "  Object.entries(latestRelays).forEach(([n,cfg])=>{"
        "    const d=document.createElement('div');"
        "    d.className='chip'+(editingRelay===n?' active':'');"
        "    d.dataset.name=n;"
        "    d.onclick=(e)=>{if(e.target.tagName!=='BUTTON')editRelay(n);};"
        "    d.innerHTML=`<strong>${n}</strong> ch=${cfg.relay_channels} port=${cfg.windows_port||cfg.linux_port||'-'} baud=${cfg.baudrate||9600}`"
        "      + ` <button class=\"danger\" onclick=\"event.stopPropagation();deleteRelay('${n}')\">删除</button>`;"
        "    rl.appendChild(d);"
        "  });"
        "  const bl=document.getElementById('boardList'); bl.innerHTML='';"
        "  Object.entries(latestBoards).forEach(([n,cfg])=>{"
        "    const d=document.createElement('div');"
        "    d.className='chip'+(editingBoard===n?' active':'');"
        "    d.dataset.name=n;"
        "    d.onclick=(e)=>{if(e.target.tagName!=='BUTTON')editBoard(n);};"
        "    d.innerHTML=`<strong>${n}</strong> reset=${cfg.reset&&cfg.reset.relay} ch${cfg.reset&&cfg.reset.channel}`"
        "      + ` <button class=\"danger\" onclick=\"event.stopPropagation();deleteBoard('${n}')\">删除</button>`;"
        "    bl.appendChild(d);"
        "  });"
        "  refreshBoardRelaySelects();"
        "  refreshPortSelects();"
        "  updateEditorHints();"
        "  updateListSelection();"
        "}"
        "function clearRelayEditor(){editingRelay='';"
        "  document.getElementById('relayName').value='';"
        "  setSelect('relayWinPort',''); setSelect('relayLinuxPort','');"
        "  setSelect('relayChannels','1'); setSelect('relayBaud','9600');"
        "  document.getElementById('relayEnabled').value='true'; document.getElementById('relayIoInv').value='false';"
        "  document.getElementById('relayStartup').value='none';"
        "  updateEditorHints(); updateListSelection();}"
        "function editRelay(name){"
        "  const c=latestRelays[name]||{}; editingRelay=name;"
        "  document.getElementById('relayName').value=name;"
        "  document.getElementById('relayEnabled').value=c.enabled===false?'false':'true';"
        "  setSelect('relayWinPort',c.windows_port||'');"
        "  setSelect('relayLinuxPort',c.linux_port||'');"
        "  setSelect('relayChannels',c.relay_channels||1);"
        "  setSelect('relayBaud',c.baudrate||9600);"
        "  document.getElementById('relayIoInv').value=c.io_inverted?'true':'false';"
        "  document.getElementById('relayStartup').value=c.startup_init||'none';"
        "  updateEditorHints(); updateListSelection();"
        "  st('relayStatus',true,'已载入: '+name);"
        "}"
        "function relayParams(){return{"
        "  name:document.getElementById('relayName').value.trim(),"
        "  enabled:document.getElementById('relayEnabled').value,"
        "  windows_port:document.getElementById('relayWinPort').value.trim(),"
        "  linux_port:document.getElementById('relayLinuxPort').value.trim(),"
        "  relay_channels:document.getElementById('relayChannels').value,"
        "  baudrate:document.getElementById('relayBaud').value,"
        "  io_inverted:document.getElementById('relayIoInv').value,"
        "  startup_init:document.getElementById('relayStartup').value"
        "};}"
        "async function createRelay(){"
        "  const p=relayParams(); if(!p.name)return st('relayStatus',false,'name required');"
        "  const r=await fetch('/api/config/relay/create?'+qs(p)); const d=await r.json();"
        "  st('relayStatus',r.ok,r.ok?'created':(d.error||'fail')); if(r.ok)loadLists();"
        "}"
        "async function updateRelay(){"
        "  if(!editingRelay)return st('relayStatus',false,'请先在上方列表选择 relay');"
        "  const p=relayParams(); p.name=editingRelay; p.new_name=document.getElementById('relayName').value.trim();"
        "  const r=await fetch('/api/config/relay/update?'+qs(p)); const d=await r.json();"
        "  st('relayStatus',r.ok,r.ok?'updated':(d.error||'fail')); if(r.ok){clearRelayEditor();loadLists();}"
        "}"
        "async function deleteRelay(n){"
        "  if(!confirm('删除 relay '+n+'?'))return;"
        "  const r=await fetch('/api/config/relay/delete?name='+encodeURIComponent(n));"
        "  const d=await r.json(); st('relayStatus',r.ok,r.ok?'deleted':(d.error||'fail'));"
        "  if(r.ok){if(editingRelay===n)clearRelayEditor();loadLists();}"
        "}"
        "function clearBoardEditor(){editingBoard='';"
        "  document.getElementById('boardName').value=''; document.getElementById('boardActions').value='';"
        "  setSelect('boardResetRelay',''); setSelect('boardUpgRelay','');"
        "  setSelect('boardResetCh','1'); setSelect('boardUpgCh','2'); setSelect('boardResetHold','5');"
        "  document.getElementById('boardEnabled').value='true'; document.getElementById('boardUpgEn').value='false';"
        "  refreshBoardChannelSelects();"
        "  updateEditorHints(); updateListSelection();"
        "}"
        "function editBoard(name){"
        "  const c=latestBoards[name]||{}; editingBoard=name;"
        "  document.getElementById('boardName').value=name;"
        "  document.getElementById('boardEnabled').value=c.enabled===false?'false':'true';"
        "  setSelect('boardResetRelay',(c.reset&&c.reset.relay)||'');"
        "  refreshBoardChannelSelects();"
        "  setSelect('boardResetCh',(c.reset&&c.reset.channel)||1);"
        "  setSelect('boardResetHold',String((c.reset&&c.reset.hold_seconds)||5));"
        "  document.getElementById('boardResetPol').value=(c.reset&&c.reset.polarity_inverted)?'true':'false';"
        "  const u=c.upgrade_mode||{};"
        "  document.getElementById('boardUpgEn').value=c.has_upgrade_mode&&u.enabled!==false?'true':'false';"
        "  setSelect('boardUpgRelay',u.relay||'');"
        "  refreshBoardChannelSelects();"
        "  setSelect('boardUpgCh',u.channel||2);"
        "  document.getElementById('boardUpgPol').value=u.polarity_inverted?'true':'false';"
        "  document.getElementById('boardActions').value=c.actions?JSON.stringify(c.actions,null,2):'';"
        "  updateEditorHints(); updateListSelection();"
        "  st('boardStatus',true,'已载入: '+name);"
        "}"
        "function boardParams(){"
        "  const aj=document.getElementById('boardActions').value.trim();"
        "  const p={"
        "    name:document.getElementById('boardName').value.trim(),"
        "    enabled:document.getElementById('boardEnabled').value,"
        "    reset_relay_name:document.getElementById('boardResetRelay').value.trim(),"
        "    reset_channel:document.getElementById('boardResetCh').value,"
        "    reset_hold_seconds:document.getElementById('boardResetHold').value,"
        "    reset_polarity_inverted:document.getElementById('boardResetPol').value,"
        "    upgrade_enabled:document.getElementById('boardUpgEn').value,"
        "    upgrade_relay_name:document.getElementById('boardUpgRelay').value.trim(),"
        "    upgrade_channel:document.getElementById('boardUpgCh').value,"
        "    upgrade_polarity_inverted:document.getElementById('boardUpgPol').value"
        "  };"
        "  if(aj)p.actions_json=aj; return p;"
        "}"
        "async function createBoard(){"
        "  const p=boardParams(); if(!p.name)return st('boardStatus',false,'name required');"
        "  const r=await fetch('/api/config/board/create?'+qs(p)); const d=await r.json();"
        "  st('boardStatus',r.ok,r.ok?'created':(d.error||'fail')); if(r.ok)loadLists();"
        "}"
        "async function updateBoard(){"
        "  if(!editingBoard)return st('boardStatus',false,'请先在上方列表选择 board');"
        "  const p=boardParams(); p.name=editingBoard; p.new_name=document.getElementById('boardName').value.trim();"
        "  const r=await fetch('/api/config/board/update?'+qs(p)); const d=await r.json();"
        "  st('boardStatus',r.ok,r.ok?'updated':(d.error||'fail')); if(r.ok){clearBoardEditor();loadLists();}"
        "}"
        "async function deleteBoard(n){"
        "  if(!confirm('删除 board '+n+'?'))return;"
        "  const r=await fetch('/api/config/board/delete?name='+encodeURIComponent(n));"
        "  const d=await r.json(); st('boardStatus',r.ok,r.ok?'deleted':(d.error||'fail'));"
        "  if(r.ok){if(editingBoard===n)clearBoardEditor();loadLists();}"
        "}"
        "async function saveServerPort(){"
        "  const p=document.getElementById('serverPort').value.trim();"
        "  const r=await fetch('/api/config/server/set?port='+encodeURIComponent(p));"
        "  const d=await r.json(); st('serverStatus',r.ok,r.ok?'port saved (restart to apply)':(d.error||'fail'));"
        "}"
        "async function reloadConfig(){"
        "  const r=await fetch('/api/config/reload'); const d=await r.json();"
        "  st('serverStatus',r.ok,r.ok?'reloaded':(d.error||'fail')); if(r.ok)loadLists();"
        "}"
        "async function initPage(){initStaticSelects();await Promise.all([loadMeta(),loadPortSelects()]);await loadLists();}"
        "initPage();"
        "</script>");

    pos += (size_t)snprintf(html + pos, cap - pos, "%s", relay_page_tail());

    mg_http_reply(c, 200, "Content-Type: text/html; charset=utf-8\r\nCache-Control: no-store\r\n", "%s", html);
    free(html);
}
